<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="12.0" os="Windows 8" host="DESKTOP-R14S24V"><DocLocation><![CDATA[E:\Jangboer201705\UFT-Demo\Demo2]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Demo2]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="182" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[登录界面]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:05]]></Time>
<TimeTick>1496213045</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[登录界面.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:05]]></Time>
<TimeTick>1496213045</TimeTick>
<NodeArgs eType="Replay" icon="185" nRep="10" Source="Action1" SourceLine="0" >
<Disp><![CDATA[登录界面.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:06]]></Time>
<TimeTick>1496213046</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[运行 "C:\Users\Administrator\Desktop\兔巢acs3.1\软件201705181100-Debug\Debug\PakingVideo_Login.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[运行 "C:\Users\Administrator\Desktop\兔巢acs3.1\软件201705181100-Debug\Debug\PakingVideo_Login.exe",1]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:06]]></Time>
<TimeTick>1496213046</TimeTick>
<NodeArgs eType="Replay" icon="186" nRep="14" status="Passed" Source="Action1" SourceLine="5" >
<Disp><![CDATA[运行 "C:\Users\Administrator\Desktop\兔巢acs3.1\软件201705181100-Debug\Debug\PakingVideo_Login.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="186" nRep="13" status="Passed" Source="Action1" SourceLine="5" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="185" nRep="9" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[登录界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[电脑终端注册]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:11]]></Time>
<TimeTick>1496213051</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[电脑终端注册.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:11]]></Time>
<TimeTick>1496213051</TimeTick>
<NodeArgs eType="Replay" icon="185" nRep="17" Source="Action1" SourceLine="10" >
<Disp><![CDATA[电脑终端注册.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="185" nRep="16" Source="Action1" SourceLine="10" >
<Disp><![CDATA[电脑终端注册]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[登录界面]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:13]]></Time>
<TimeTick>1496213053</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[SwfEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:13]]></Time>
<TimeTick>1496213053</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="20" Source="Action1" SourceLine="21" >
<Disp><![CDATA[SwfEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[SwfEdit_2.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5924e4b99935029c317c8fdbcdda0b6b"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:13]]></Time>
<TimeTick>1496213053</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="22" Source="Action1" SourceLine="22" >
<Disp><![CDATA[SwfEdit_2.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[登录.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:15]]></Time>
<TimeTick>1496213055</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="24" Source="Action1" SourceLine="25" >
<Disp><![CDATA[登录.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="185" nRep="19" Source="Action1" SourceLine="21" >
<Disp><![CDATA[登录界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[配置向导]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:30]]></Time>
<TimeTick>1496213070</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[配置向导.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:30]]></Time>
<TimeTick>1496213070</TimeTick>
<NodeArgs eType="Replay" icon="185" nRep="27" Source="Action1" SourceLine="30" >
<Disp><![CDATA[配置向导.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="185" nRep="26" Source="Action1" SourceLine="30" >
<Disp><![CDATA[配置向导]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[视频识别出入口管理系统]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:30]]></Time>
<TimeTick>1496213070</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[视频识别出入口管理系统.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:30]]></Time>
<TimeTick>1496213070</TimeTick>
<NodeArgs eType="Replay" icon="185" nRep="29" Source="Action1" SourceLine="38" >
<Disp><![CDATA[视频识别出入口管理系统.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[设备管理.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:30]]></Time>
<TimeTick>1496213070</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="31" Source="Action1" SourceLine="43" >
<Disp><![CDATA[设备管理.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[btnMenu1.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:31]]></Time>
<TimeTick>1496213071</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="33" Source="Action1" SourceLine="47" >
<Disp><![CDATA[btnMenu1.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="185" nRep="28" Source="Action1" SourceLine="38" >
<Disp><![CDATA[视频识别出入口管理系统]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[区域管理]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:33]]></Time>
<TimeTick>1496213073</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[区域管理.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:33]]></Time>
<TimeTick>1496213073</TimeTick>
<NodeArgs eType="Replay" icon="185" nRep="35" Source="Action1" SourceLine="51" >
<Disp><![CDATA[区域管理.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[添加(A).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:33]]></Time>
<TimeTick>1496213073</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="37" Source="Action1" SourceLine="55" >
<Disp><![CDATA[添加(A).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[区域设置]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:34]]></Time>
<TimeTick>1496213074</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[区域设置.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:34]]></Time>
<TimeTick>1496213074</TimeTick>
<NodeArgs eType="Replay" icon="185" nRep="40" Source="Action1" SourceLine="58" >
<Disp><![CDATA[区域设置.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[SwfEdit_3.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["添加区域Test"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:34]]></Time>
<TimeTick>1496213074</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="42" Source="Action1" SourceLine="65" >
<Disp><![CDATA[SwfEdit_3.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[SwfEdit_2.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micDel "]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:37]]></Time>
<TimeTick>1496213077</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="44" Source="Action1" SourceLine="70" >
<Disp><![CDATA[SwfEdit_2.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[SwfEdit_2.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micDel "]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:37]]></Time>
<TimeTick>1496213077</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="46" Source="Action1" SourceLine="70" >
<Disp><![CDATA[SwfEdit_2.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[SwfEdit_2.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micDel "]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:37]]></Time>
<TimeTick>1496213077</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="48" Source="Action1" SourceLine="70" >
<Disp><![CDATA[SwfEdit_2.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[SwfEdit_2.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micDel "]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:37]]></Time>
<TimeTick>1496213077</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="50" Source="Action1" SourceLine="70" >
<Disp><![CDATA[SwfEdit_2.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[SwfEdit_2.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micDel "]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:37]]></Time>
<TimeTick>1496213077</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="52" Source="Action1" SourceLine="70" >
<Disp><![CDATA[SwfEdit_2.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[SwfEdit_2.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micDel "]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:37]]></Time>
<TimeTick>1496213077</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="54" Source="Action1" SourceLine="70" >
<Disp><![CDATA[SwfEdit_2.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[SwfEdit_2.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["120"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:37]]></Time>
<TimeTick>1496213077</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="56" Source="Action1" SourceLine="73" >
<Disp><![CDATA[SwfEdit_2.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[SwfEdit.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micDel "]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:41]]></Time>
<TimeTick>1496213081</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="58" Source="Action1" SourceLine="78" >
<Disp><![CDATA[SwfEdit.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[SwfEdit.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micDel "]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:42]]></Time>
<TimeTick>1496213082</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="60" Source="Action1" SourceLine="78" >
<Disp><![CDATA[SwfEdit.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[SwfEdit.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micDel "]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:42]]></Time>
<TimeTick>1496213082</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="62" Source="Action1" SourceLine="78" >
<Disp><![CDATA[SwfEdit.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[SwfEdit.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micDel "]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:43]]></Time>
<TimeTick>1496213083</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="64" Source="Action1" SourceLine="78" >
<Disp><![CDATA[SwfEdit.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[SwfEdit.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micDel "]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:43]]></Time>
<TimeTick>1496213083</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="66" Source="Action1" SourceLine="78" >
<Disp><![CDATA[SwfEdit.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[SwfEdit.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micDel "]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:44]]></Time>
<TimeTick>1496213084</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="68" Source="Action1" SourceLine="78" >
<Disp><![CDATA[SwfEdit.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[SwfEdit.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["10"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:44]]></Time>
<TimeTick>1496213084</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="70" Source="Action1" SourceLine="81" >
<Disp><![CDATA[SwfEdit.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[radGpIsInternl.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[19, 17]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:48]]></Time>
<TimeTick>1496213088</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="72" Source="Action1" SourceLine="89" >
<Disp><![CDATA[radGpIsInternl.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[保存.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:49]]></Time>
<TimeTick>1496213089</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="74" Source="Action1" SourceLine="93" >
<Disp><![CDATA[保存.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="185" nRep="39" Source="Action1" SourceLine="58" >
<Disp><![CDATA[区域设置]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Replay method]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0, "添加区域Test"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:49]]></Time>
<TimeTick>1496213089</TimeTick>
<NodeArgs eType="Replay" icon="189" nRep="76" nType="SwfTable" Source="Action1" SourceLine="99" >
<Disp><![CDATA[Replay method]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Replay method]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 1, "120"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:50]]></Time>
<TimeTick>1496213090</TimeTick>
<NodeArgs eType="Replay" icon="189" nRep="78" nType="SwfTable" Source="Action1" SourceLine="101" >
<Disp><![CDATA[Replay method]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Replay method]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 2, "10"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:50]]></Time>
<TimeTick>1496213090</TimeTick>
<NodeArgs eType="Replay" icon="189" nRep="80" nType="SwfTable" Source="Action1" SourceLine="102" >
<Disp><![CDATA[Replay method]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[区域管理.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:50]]></Time>
<TimeTick>1496213090</TimeTick>
<NodeArgs eType="Replay" icon="185" nRep="82" Source="Action1" SourceLine="105" >
<Disp><![CDATA[区域管理.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="185" nRep="34" Source="Action1" SourceLine="51" >
<Disp><![CDATA[区域管理]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[Add]]></Obj>
<Details ><![CDATA[添加成功！]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:51]]></Time>
<TimeTick>1496213091</TimeTick>
<NodeArgs eType="User" icon="190" nRep="83" status="Passed" Source="Action1" SourceLine="114" >
<Disp><![CDATA[Add]]></Disp>
</NodeArgs>
</Step>
<Action rID="T48">
<AName><![CDATA[临时时长收费]]></AName>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[视频识别出入口管理系统]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:52]]></Time>
<TimeTick>1496213092</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[系统设置.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:52]]></Time>
<TimeTick>1496213092</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="87" Source="临时时长收费" SourceLine="23" >
<Disp><![CDATA[系统设置.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[btnMenu4.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:53]]></Time>
<TimeTick>1496213093</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="89" Source="临时时长收费" SourceLine="25" >
<Disp><![CDATA[btnMenu4.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="185" nRep="86" Source="临时时长收费" SourceLine="23" >
<Disp><![CDATA[视频识别出入口管理系统]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[收费规则管理]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:54]]></Time>
<TimeTick>1496213094</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[收费规则管理.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:54]]></Time>
<TimeTick>1496213094</TimeTick>
<NodeArgs eType="Replay" icon="185" nRep="91" Source="临时时长收费" SourceLine="30" >
<Disp><![CDATA[收费规则管理.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[rdoChannelType.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[124, 12]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:55]]></Time>
<TimeTick>1496213095</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="93" Source="临时时长收费" SourceLine="36" >
<Disp><![CDATA[rdoChannelType.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[添加(A).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:56]]></Time>
<TimeTick>1496213096</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="95" Source="临时时长收费" SourceLine="39" >
<Disp><![CDATA[添加(A).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[编辑收费规则]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:57]]></Time>
<TimeTick>1496213097</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[编辑收费规则.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:57]]></Time>
<TimeTick>1496213097</TimeTick>
<NodeArgs eType="Replay" icon="185" nRep="97" Source="临时时长收费" SourceLine="41" >
<Disp><![CDATA[编辑收费规则.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[cmbChargeType.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:58]]></Time>
<TimeTick>1496213098</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="99" Source="临时时长收费" SourceLine="46" >
<Disp><![CDATA[cmbChargeType.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="185" nRep="96" Source="临时时长收费" SourceLine="41" >
<Disp><![CDATA[编辑收费规则]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="185" nRep="90" Source="临时时长收费" SourceLine="30" >
<Disp><![CDATA[收费规则管理]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[SwfWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:59]]></Time>
<TimeTick>1496213099</TimeTick>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[SwfObject.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[65, 8]]></Details>
<Time><![CDATA[2017-05-31 - 14:44:59]]></Time>
<TimeTick>1496213099</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="102" Source="临时时长收费" SourceLine="49" >
<Disp><![CDATA[SwfObject.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="185" nRep="101" Source="临时时长收费" SourceLine="49" >
<Disp><![CDATA[SwfWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[收费规则管理]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:01]]></Time>
<TimeTick>1496213101</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[编辑收费规则]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:01]]></Time>
<TimeTick>1496213101</TimeTick>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[SwfEdit_8.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["临时时间收费-分时收费"]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:01]]></Time>
<TimeTick>1496213101</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="106" Source="临时时长收费" SourceLine="53" >
<Disp><![CDATA[SwfEdit_8.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[rdoChargeType.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[36, 13]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:02]]></Time>
<TimeTick>1496213102</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="108" Source="临时时长收费" SourceLine="57" >
<Disp><![CDATA[rdoChargeType.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[SwfEdit_7.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["15"]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:04]]></Time>
<TimeTick>1496213104</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="110" Source="临时时长收费" SourceLine="62" >
<Disp><![CDATA[SwfEdit_7.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[SwfEdit_6.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["24"]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:06]]></Time>
<TimeTick>1496213106</TimeTick>
<NodeArgs eType="Replay" icon="187" nRep="112" Source="临时时长收费" SourceLine="67" >
<Disp><![CDATA[SwfEdit_6.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[txtStartTime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:09]]></Time>
<TimeTick>1496213109</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="114" Source="临时时长收费" SourceLine="110" >
<Disp><![CDATA[txtStartTime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[txtStartTime.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micLeft "]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:10]]></Time>
<TimeTick>1496213110</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="116" Source="临时时长收费" SourceLine="112" >
<Disp><![CDATA[txtStartTime.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[txtStartTime.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micLeft "]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:10]]></Time>
<TimeTick>1496213110</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="118" Source="临时时长收费" SourceLine="112" >
<Disp><![CDATA[txtStartTime.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[txtStartTime.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micLeft "]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:11]]></Time>
<TimeTick>1496213111</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="120" Source="临时时长收费" SourceLine="112" >
<Disp><![CDATA[txtStartTime.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[txtStartTime.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["0"]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:11]]></Time>
<TimeTick>1496213111</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="122" Source="临时时长收费" SourceLine="117" >
<Disp><![CDATA[txtStartTime.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[txtStartTime.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micRight "]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:13]]></Time>
<TimeTick>1496213113</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="124" Source="临时时长收费" SourceLine="119" >
<Disp><![CDATA[txtStartTime.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[txtStartTime.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["00"]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:13]]></Time>
<TimeTick>1496213113</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="126" Source="临时时长收费" SourceLine="117" >
<Disp><![CDATA[txtStartTime.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[txtStartTime.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" micRight "]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:15]]></Time>
<TimeTick>1496213115</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="128" Source="临时时长收费" SourceLine="119" >
<Disp><![CDATA[txtStartTime.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[txtStartTime.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["00"]]></Details>
<Time><![CDATA[2017-05-31 - 14:45:15]]></Time>
<TimeTick>1496213115</TimeTick>
<NodeArgs eType="Replay" icon="188" nRep="130" Source="临时时长收费" SourceLine="117" >
<Disp><![CDATA[txtStartTime.Type]]></Disp>