<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="12.0" os="Windows 8" host="DESKTOP-R14S24V"><DocLocation><![CDATA[E:\Jangboer201705\UFT-YeWu\ACS3.1-All\Login]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Login]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="654" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[AddUser]]></AName>
<AIter rID="T5" iterID="1" isCountable="False" >
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[视频识别出入口管理系统]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:25]]></Time>
<TimeTick>1496302825</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[视频识别出入口管理系统.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:25]]></Time>
<TimeTick>1496302825</TimeTick>
<NodeArgs eType="Replay" icon="657" nRep="10" Source="AddUser" SourceLine="3" >
<Disp><![CDATA[视频识别出入口管理系统.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:28]]></Time>
<TimeTick>1496302828</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[运行 "C:\Users\Administrator\Desktop\兔巢acs3.1\软件201705181100-Debug\Debug\PakingVideo_Login.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[运行 "C:\Users\Administrator\Desktop\兔巢acs3.1\软件201705181100-Debug\Debug\PakingVideo_Login.exe",1]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:28]]></Time>
<TimeTick>1496302828</TimeTick>
<NodeArgs eType="Replay" icon="658" nRep="14" status="Passed" Source="AddUser" SourceLine="10" >
<Disp><![CDATA[运行 "C:\Users\Administrator\Desktop\兔巢acs3.1\软件201705181100-Debug\Debug\PakingVideo_Login.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="658" nRep="13" status="Passed" Source="AddUser" SourceLine="10" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="657" nRep="9" status="Passed" Source="AddUser" SourceLine="3" >
<Disp><![CDATA[视频识别出入口管理系统]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[登录界面]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:30]]></Time>
<TimeTick>1496302830</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[SwfEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["lfzdh"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:30]]></Time>
<TimeTick>1496302830</TimeTick>
<NodeArgs eType="Replay" icon="659" nRep="17" Source="AddUser" SourceLine="15" >
<Disp><![CDATA[SwfEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[SwfEdit_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["lfzdh"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:30]]></Time>
<TimeTick>1496302830</TimeTick>
<NodeArgs eType="Replay" icon="659" nRep="19" Source="AddUser" SourceLine="16" >
<Disp><![CDATA[SwfEdit_2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[登录.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:30]]></Time>
<TimeTick>1496302830</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="21" Source="AddUser" SourceLine="17" >
<Disp><![CDATA[登录.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="657" nRep="16" Source="AddUser" SourceLine="15" >
<Disp><![CDATA[登录界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[视频识别出入口管理系统]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:33]]></Time>
<TimeTick>1496302833</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[视频识别出入口管理系统.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:33]]></Time>
<TimeTick>1496302833</TimeTick>
<NodeArgs eType="Replay" icon="657" nRep="24" Source="AddUser" SourceLine="21" >
<Disp><![CDATA[视频识别出入口管理系统.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[系统设置.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:33]]></Time>
<TimeTick>1496302833</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="26" Source="AddUser" SourceLine="23" >
<Disp><![CDATA[系统设置.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[btnMenu2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:34]]></Time>
<TimeTick>1496302834</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="28" Source="AddUser" SourceLine="24" >
<Disp><![CDATA[btnMenu2.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="657" nRep="23" Source="AddUser" SourceLine="21" >
<Disp><![CDATA[视频识别出入口管理系统]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[操作员管理]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:35]]></Time>
<TimeTick>1496302835</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[操作员管理.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:35]]></Time>
<TimeTick>1496302835</TimeTick>
<NodeArgs eType="Replay" icon="657" nRep="31" Source="AddUser" SourceLine="29" >
<Disp><![CDATA[操作员管理.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[添加(A).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:35]]></Time>
<TimeTick>1496302835</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="33" Source="AddUser" SourceLine="30" >
<Disp><![CDATA[添加(A).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[操作员编辑]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:35]]></Time>
<TimeTick>1496302835</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[SwfEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:35]]></Time>
<TimeTick>1496302835</TimeTick>
<NodeArgs eType="Replay" icon="659" nRep="36" Source="AddUser" SourceLine="34" >
<Disp><![CDATA[SwfEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[cmbRole.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:35]]></Time>
<TimeTick>1496302835</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="38" Source="AddUser" SourceLine="39" >
<Disp><![CDATA[cmbRole.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[SwfEdit_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:35]]></Time>
<TimeTick>1496302835</TimeTick>
<NodeArgs eType="Replay" icon="659" nRep="40" Source="AddUser" SourceLine="42" >
<Disp><![CDATA[SwfEdit_2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[SwfEdit_3.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:35]]></Time>
<TimeTick>1496302835</TimeTick>
<NodeArgs eType="Replay" icon="659" nRep="42" Source="AddUser" SourceLine="44" >
<Disp><![CDATA[SwfEdit_3.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[保存(S).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:37]]></Time>
<TimeTick>1496302837</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="44" Source="AddUser" SourceLine="47" >
<Disp><![CDATA[保存(S).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[提示信息]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:37]]></Time>
<TimeTick>1496302837</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[提示信息.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:37]]></Time>
<TimeTick>1496302837</TimeTick>
<NodeArgs eType="Replay" icon="657" nRep="46" Source="AddUser" SourceLine="49" >
<Disp><![CDATA[提示信息.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:38]]></Time>
<TimeTick>1496302838</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="48" Source="AddUser" SourceLine="51" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="657" nRep="45" Source="AddUser" SourceLine="49" >
<Disp><![CDATA[提示信息]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[操作员编辑.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:39]]></Time>
<TimeTick>1496302839</TimeTick>
<NodeArgs eType="Replay" icon="657" nRep="51" Source="AddUser" SourceLine="54" >
<Disp><![CDATA[操作员编辑.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="657" nRep="35" Source="AddUser" SourceLine="34" >
<Disp><![CDATA[操作员编辑]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Replay method]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 1, "超级管理员"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:41]]></Time>
<TimeTick>1496302841</TimeTick>
<NodeArgs eType="Replay" icon="661" nRep="53" nType="SwfTable" Source="AddUser" SourceLine="73" >
<Disp><![CDATA[Replay method]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Replay method]]></Obj>
<Details plainTxt="False" ><![CDATA[1, 1, "收费员1"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:42]]></Time>
<TimeTick>1496302842</TimeTick>
<NodeArgs eType="Replay" icon="661" nRep="55" nType="SwfTable" Source="AddUser" SourceLine="73" >
<Disp><![CDATA[Replay method]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Replay method]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 1, "收费员2"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:42]]></Time>
<TimeTick>1496302842</TimeTick>
<NodeArgs eType="Replay" icon="661" nRep="57" nType="SwfTable" Source="AddUser" SourceLine="73" >
<Disp><![CDATA[Replay method]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Replay method]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 1, "zwj"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:42]]></Time>
<TimeTick>1496302842</TimeTick>
<NodeArgs eType="Replay" icon="661" nRep="59" nType="SwfTable" Source="AddUser" SourceLine="73" >
<Disp><![CDATA[Replay method]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Replay method]]></Obj>
<Details plainTxt="False" ><![CDATA[4, 1, "admin"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:43]]></Time>
<TimeTick>1496302843</TimeTick>
<NodeArgs eType="Replay" icon="661" nRep="61" nType="SwfTable" Source="AddUser" SourceLine="73" >
<Disp><![CDATA[Replay method]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[gridControlOperator.ActivateCell]]></Obj>
<Details plainTxt="False" ><![CDATA[4, 1]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:43]]></Time>
<TimeTick>1496302843</TimeTick>
<NodeArgs eType="Replay" icon="661" nRep="63" Source="AddUser" SourceLine="76" >
<Disp><![CDATA[gridControlOperator.ActivateCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[操作员编辑]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:44]]></Time>
<TimeTick>1496302844</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[SwfEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Editadmin"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:44]]></Time>
<TimeTick>1496302844</TimeTick>
<NodeArgs eType="Replay" icon="659" nRep="66" Source="AddUser" SourceLine="78" >
<Disp><![CDATA[SwfEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[cmbRole.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:44]]></Time>
<TimeTick>1496302844</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="68" Source="AddUser" SourceLine="82" >
<Disp><![CDATA[cmbRole.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[SwfEdit_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Editadmin"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:45]]></Time>
<TimeTick>1496302845</TimeTick>
<NodeArgs eType="Replay" icon="659" nRep="70" Source="AddUser" SourceLine="86" >
<Disp><![CDATA[SwfEdit_2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[SwfEdit_3.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Editadmin"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:45]]></Time>
<TimeTick>1496302845</TimeTick>
<NodeArgs eType="Replay" icon="659" nRep="72" Source="AddUser" SourceLine="88" >
<Disp><![CDATA[SwfEdit_3.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[保存(S).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:46]]></Time>
<TimeTick>1496302846</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="74" Source="AddUser" SourceLine="90" >
<Disp><![CDATA[保存(S).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[提示信息]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:47]]></Time>
<TimeTick>1496302847</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[提示信息.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:47]]></Time>
<TimeTick>1496302847</TimeTick>
<NodeArgs eType="Replay" icon="657" nRep="76" Source="AddUser" SourceLine="91" >
<Disp><![CDATA[提示信息.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:48]]></Time>
<TimeTick>1496302848</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="78" Source="AddUser" SourceLine="93" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="657" nRep="75" Source="AddUser" SourceLine="91" >
<Disp><![CDATA[提示信息]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[操作员编辑.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:50]]></Time>
<TimeTick>1496302850</TimeTick>
<NodeArgs eType="Replay" icon="657" nRep="81" Source="AddUser" SourceLine="95" >
<Disp><![CDATA[操作员编辑.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="657" nRep="65" Source="AddUser" SourceLine="78" >
<Disp><![CDATA[操作员编辑]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[操作员管理.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:50]]></Time>
<TimeTick>1496302850</TimeTick>
<NodeArgs eType="Replay" icon="657" nRep="83" Source="AddUser" SourceLine="109" >
<Disp><![CDATA[操作员管理.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="657" nRep="30" Source="AddUser" SourceLine="29" >
<Disp><![CDATA[操作员管理]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="655" nRep="8" status="Passed" >
<Disp><![CDATA[AddUser 迭代 1 (行 1)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T48" iterID="2" isCountable="False" >
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[视频识别出入口管理系统]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:51]]></Time>
<TimeTick>1496302851</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[视频识别出入口管理系统.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:51]]></Time>
<TimeTick>1496302851</TimeTick>
<NodeArgs eType="Replay" icon="657" nRep="87" Source="AddUser" SourceLine="3" >
<Disp><![CDATA[视频识别出入口管理系统.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:53]]></Time>
<TimeTick>1496302853</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[运行 "C:\Users\Administrator\Desktop\兔巢acs3.1\软件201705181100-Debug\Debug\PakingVideo_Login.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[运行 "C:\Users\Administrator\Desktop\兔巢acs3.1\软件201705181100-Debug\Debug\PakingVideo_Login.exe",1]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:53]]></Time>
<TimeTick>1496302853</TimeTick>
<NodeArgs eType="Replay" icon="658" nRep="91" status="Passed" Source="AddUser" SourceLine="10" >
<Disp><![CDATA[运行 "C:\Users\Administrator\Desktop\兔巢acs3.1\软件201705181100-Debug\Debug\PakingVideo_Login.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="658" nRep="90" status="Passed" Source="AddUser" SourceLine="10" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="657" nRep="86" status="Passed" Source="AddUser" SourceLine="3" >
<Disp><![CDATA[视频识别出入口管理系统]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[登录界面]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:55]]></Time>
<TimeTick>1496302855</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[SwfEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["lfzdh"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:55]]></Time>
<TimeTick>1496302855</TimeTick>
<NodeArgs eType="Replay" icon="659" nRep="94" Source="AddUser" SourceLine="15" >
<Disp><![CDATA[SwfEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[SwfEdit_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["lfzdh"]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:56]]></Time>
<TimeTick>1496302856</TimeTick>
<NodeArgs eType="Replay" icon="659" nRep="96" Source="AddUser" SourceLine="16" >
<Disp><![CDATA[SwfEdit_2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[登录.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:56]]></Time>
<TimeTick>1496302856</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="98" Source="AddUser" SourceLine="17" >
<Disp><![CDATA[登录.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="657" nRep="93" Source="AddUser" SourceLine="15" >
<Disp><![CDATA[登录界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[视频识别出入口管理系统]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:59]]></Time>
<TimeTick>1496302859</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[视频识别出入口管理系统.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:59]]></Time>
<TimeTick>1496302859</TimeTick>
<NodeArgs eType="Replay" icon="657" nRep="101" Source="AddUser" SourceLine="21" >
<Disp><![CDATA[视频识别出入口管理系统.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[系统设置.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:40:59]]></Time>
<TimeTick>1496302859</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="103" Source="AddUser" SourceLine="23" >
<Disp><![CDATA[系统设置.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[btnMenu2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:00]]></Time>
<TimeTick>1496302860</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="105" Source="AddUser" SourceLine="24" >
<Disp><![CDATA[btnMenu2.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="657" nRep="100" Source="AddUser" SourceLine="21" >
<Disp><![CDATA[视频识别出入口管理系统]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[操作员管理]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:02]]></Time>
<TimeTick>1496302862</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[操作员管理.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:02]]></Time>
<TimeTick>1496302862</TimeTick>
<NodeArgs eType="Replay" icon="657" nRep="108" Source="AddUser" SourceLine="29" >
<Disp><![CDATA[操作员管理.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[添加(A).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:02]]></Time>
<TimeTick>1496302862</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="110" Source="AddUser" SourceLine="30" >
<Disp><![CDATA[添加(A).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[操作员编辑]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:02]]></Time>
<TimeTick>1496302862</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[SwfEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin1"]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:02]]></Time>
<TimeTick>1496302862</TimeTick>
<NodeArgs eType="Replay" icon="659" nRep="113" Source="AddUser" SourceLine="34" >
<Disp><![CDATA[SwfEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[cmbRole.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:02]]></Time>
<TimeTick>1496302862</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="115" Source="AddUser" SourceLine="39" >
<Disp><![CDATA[cmbRole.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[SwfEdit_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin1"]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:03]]></Time>
<TimeTick>1496302863</TimeTick>
<NodeArgs eType="Replay" icon="659" nRep="117" Source="AddUser" SourceLine="42" >
<Disp><![CDATA[SwfEdit_2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[SwfEdit_3.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin1"]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:03]]></Time>
<TimeTick>1496302863</TimeTick>
<NodeArgs eType="Replay" icon="659" nRep="119" Source="AddUser" SourceLine="44" >
<Disp><![CDATA[SwfEdit_3.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[保存(S).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:04]]></Time>
<TimeTick>1496302864</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="121" Source="AddUser" SourceLine="47" >
<Disp><![CDATA[保存(S).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[提示信息]]></Obj>
<Details plainTxt="False" ><![CDATA[SwfWindow]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:05]]></Time>
<TimeTick>1496302865</TimeTick>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[提示信息.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:05]]></Time>
<TimeTick>1496302865</TimeTick>
<NodeArgs eType="Replay" icon="657" nRep="123" Source="AddUser" SourceLine="49" >
<Disp><![CDATA[提示信息.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:06]]></Time>
<TimeTick>1496302866</TimeTick>
<NodeArgs eType="Replay" icon="660" nRep="125" Source="AddUser" SourceLine="51" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="657" nRep="122" Source="AddUser" SourceLine="49" >
<Disp><![CDATA[提示信息]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[操作员编辑.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:08]]></Time>
<TimeTick>1496302868</TimeTick>
<NodeArgs eType="Replay" icon="657" nRep="128" Source="AddUser" SourceLine="54" >
<Disp><![CDATA[操作员编辑.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="657" nRep="112" Source="AddUser" SourceLine="34" >
<Disp><![CDATA[操作员编辑]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[Replay method]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 1, "超级管理员"]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:09]]></Time>
<TimeTick>1496302869</TimeTick>
<NodeArgs eType="Replay" icon="661" nRep="130" nType="SwfTable" Source="AddUser" SourceLine="73" >
<Disp><![CDATA[Replay method]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[Replay method]]></Obj>
<Details plainTxt="False" ><![CDATA[1, 1, "收费员1"]]></Details>
<Time><![CDATA[2017-06-01 - 15:41:10]]></Time>